# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        self.deger_edit = QtWidgets.QLineEdit(Form)
        self.deger_edit.setGeometry(QtCore.QRect(130, 100, 81, 22))
        self.deger_edit.setObjectName("deger_edit")
        self.sutun1_edit = QtWidgets.QLineEdit(Form)
        self.sutun1_edit.setGeometry(QtCore.QRect(230, 100, 81, 22))
        self.sutun1_edit.setObjectName("sutun1_edit")
        self.sutun2_edit = QtWidgets.QLineEdit(Form)
        self.sutun2_edit.setGeometry(QtCore.QRect(320, 100, 81, 22))
        self.sutun2_edit.setObjectName("sutun2_edit")
        self.show_ozellik_edit = QtWidgets.QLineEdit(Form)
        self.show_ozellik_edit.setGeometry(QtCore.QRect(130, 190, 81, 22))
        self.show_ozellik_edit.setObjectName("show_ozellik_edit")
        self.oran_edit = QtWidgets.QLineEdit(Form)
        self.oran_edit.setGeometry(QtCore.QRect(230, 190, 81, 22))
        self.oran_edit.setObjectName("oran_edit")
        self.therad_sayisi_edit = QtWidgets.QLineEdit(Form)
        self.therad_sayisi_edit.setGeometry(QtCore.QRect(320, 190, 81, 22))
        self.therad_sayisi_edit.setObjectName("therad_sayisi_edit")
        self.Getir = QtWidgets.QPushButton(Form)
        self.Getir.setGeometry(QtCore.QRect(190, 240, 93, 28))
        self.Getir.setObjectName("Getir")
        self.deger_label = QtWidgets.QLabel(Form)
        self.deger_label.setGeometry(QtCore.QRect(140, 70, 55, 21))
        self.deger_label.setObjectName("deger_label")
        self.sutun1_label = QtWidgets.QLabel(Form)
        self.sutun1_label.setGeometry(QtCore.QRect(240, 70, 55, 21))
        self.sutun1_label.setObjectName("sutun1_label")
        self.sutun2_label = QtWidgets.QLabel(Form)
        self.sutun2_label.setGeometry(QtCore.QRect(330, 70, 55, 21))
        self.sutun2_label.setObjectName("sutun2_label")
        self.show_ozellik_lael = QtWidgets.QLabel(Form)
        self.show_ozellik_lael.setGeometry(QtCore.QRect(130, 140, 81, 51))
        self.show_ozellik_lael.setObjectName("show_ozellik_lael")
        self.oran_label = QtWidgets.QLabel(Form)
        self.oran_label.setGeometry(QtCore.QRect(240, 150, 55, 21))
        self.oran_label.setObjectName("oran_label")
        self.thread_sayisi_label = QtWidgets.QLabel(Form)
        self.thread_sayisi_label.setGeometry(QtCore.QRect(330, 135, 55, 51))
        self.thread_sayisi_label.setObjectName("thread_sayisi_label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 70, 105, 52))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ozellik_label = QtWidgets.QLabel(self.widget)
        self.ozellik_label.setObjectName("ozellik_label")
        self.verticalLayout.addWidget(self.ozellik_label)
        self.ozellik_combobox = QtWidgets.QComboBox(self.widget)
        self.ozellik_combobox.setObjectName("ozellik_combobox")
        self.ozellik_combobox.addItem("")
        self.ozellik_combobox.addItem("")
        self.ozellik_combobox.addItem("")
        self.verticalLayout.addWidget(self.ozellik_combobox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Getir.setText(_translate("Form", "Getir"))
        self.deger_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Değer</span></p></body></html>"))
        self.sutun1_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Sütun1</span></p></body></html>"))
        self.sutun2_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Sütun2</span></p></body></html>"))
        self.show_ozellik_lael.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Gösterilecek</span></p><p align=\"center\"><span style=\" font-size:9pt;\">Özellik</span></p></body></html>"))
        self.oran_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Oran</span></p></body></html>"))
        self.thread_sayisi_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Thread </span></p><p align=\"center\"><span style=\" font-size:9pt;\">Sayısı</span></p></body></html>"))
        self.ozellik_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Özellik</span></p></body></html>"))
        self.ozellik_combobox.setItemText(0, _translate("Form", "Complaint ID"))
        self.ozellik_combobox.setItemText(1, _translate("Form", "ZIP Code"))
        self.ozellik_combobox.setItemText(2, _translate("Form", "State"))
