# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal


class Ui_text(object):

    update_text_line=pyqtSignal(str)
    def setupUi(self, text):
        text.setObjectName("text")
        text.resize(895, 677)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(text)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 871, 651))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(text)
        QtCore.QMetaObject.connectSlotsByName(text)
    def update_text_line(self,text):
        self.plainTextEdit.appendPlainText(text)
    def retranslateUi(self, text):
        _translate = QtCore.QCoreApplication.translate
        text.setWindowTitle(_translate("text", "Form"))
